import { v4 as uuid } from 'uuid'
import ROUTES from './routes'
import { LESSON_STATUS, PracticeTypes } from '@/types'

export const Lessons = [
  {
    id: uuid(),
    number: 1,
    slug: `The_best_job`,
    topic: `The best job`,
    lessonContent: {
      vocabulary: [
        {
          id: uuid(),
          en: 'accomplish',
          ua: 'виконувати',
          transcription: '[əˈkʌmplɪʃ]',
          definition: 'achieve or complete successfully',
          synonyms: ['make', 'commit', 'carry out'],
          example: 'Think of what you could accomplish with a real budget.',
        },
        {
          id: uuid(),
          en: 'accountant',
          ua: 'бухгалтер',
          transcription: '[əˈkaʊntənt]',
          definition: 'a person whose job is to keep or inspect financial accounts',
          synonyms: ['auditor', 'comptroller', 'controller'],
          example: `Hi, my name is Jae Park. I used to be a Computer Science major but now I'm an accountant.`,
        },
        {
          id: uuid(),
          en: 'ambition',
          ua: 'ціль',
          transcription: '[æmˈbɪʃən]',
          definition: 'a strong desire to do or achieve something',
          synonyms: ['goal', 'dream', 'vision'],
          example:
            'He lost his ambition and forgot everything but his love for this unworthy woman.',
        },
        {
          id: uuid(),
          en: 'apply for',
          ua: 'подавати заявку',
          transcription: '[əˈplaɪ fɔːr]',
          definition: 'to make a formal application or request',
          synonyms: ['ask', 'demand'],
          example: 'Any student could apply for a scholarship.',
        },
        {
          id: uuid(),
          en: 'break',
          ua: 'перерва',
          transcription: '[breɪk]',
          definition:
            'to interrupt or to stop something for a short period: a period of time when you stop working in order to rest, eat etc',
          synonyms: ['intermission', 'recess', 'part'],
          example:
            'She was taking back a library book when she tripped and fell to the ground breaking both her shoulder and part of her upper left arm .',
        },
        {
          id: uuid(),
          en: 'chairman',
          ua: 'голова',
          transcription: '[ˈtʃeəmən]',
          definition: 'a person chosen to preside over a meeting',
          synonyms: ['speaker', 'chairperson', 'chair'],
          example: 'Archibald is the chairman , president and chief executive of the company.',
        },
        {
          id: uuid(),
          en: 'deal with',
          ua: `впоратись з`,
          transcription: '[diːl wɪð]',
          definition:
            'if you deal with an unpleasant emotion or an emotionally difficult situation, you recognize it, and remain calm and in control of yourself in spite of it',
          synonyms: ['manage', 'handle', 'take on'],
          example: `He's a hard man to deal with.`,
        },
        {
          id: uuid(),
          en: 'fashion designer',
          ua: 'модельєр',
          transcription: '[ˈfæʃən dɪˈzaɪnər]',
          definition: 'a person who designs high-fashion clothing',
          synonyms: ['designer', 'Couturier'],
          example:
            'Like other artists, fashion designers are somewhat sensitive and can be competitive.',
        },
        {
          id: uuid(),
          en: 'fire',
          ua: 'звільняти',
          transcription: '[faɪər]',
          definition:
            'the state of burning that produces flames that send out heat and light, and might produce smoke; to remove someone from their job',
          synonyms: ['terminate', 'dismiss', 'can'],
          example: `You can't fire somebody because he follows his heart.`,
        },
        {
          id: uuid(),
          en: 'flexible hours',
          ua: 'гнучкий графік',
          transcription: '[ˈfleksɪbl̩ aʊərz]',
          definition: 'flexible hours allow workers to alter workday start and finish times',
          synonyms: ['Flextime'],
          example: 'Flexible hours benefit everyone.',
        },
        {
          id: uuid(),
          en: 'insurance agent',
          ua: 'страховий агент',
          transcription: '[ɪnˈʃɔːrənts ˈeɪdʒənt]',
          definition: 'a person employed to sell insurance policies',
          synonyms: ['underwriter'],
          example:
            'A well-designed succession plan will likely involve other professionals such as an attorney, appraiser and insurance agent .',
        },
        {
          id: uuid(),
          en: 'job interview',
          ua: 'співбесіда',
          transcription: '[dʒɒb ˈɪntəvjuː]',
          definition:
            'a formal meeting in which an applicant is asked questions to determine their suitability for a particular job',
          synonyms: ['job hunting'],
          example: `She talked constantly, wouldn't accept authority and had such a short span of attention that she'd probably wander off to make herself a coffee during the initial job interview`,
        },
        {
          id: uuid(),
          en: 'judge',
          ua: 'суддя',
          transcription: '[dʒʌdʒ]',
          definition:
            'a person who is in charge of a trial in a court and decides how a person who is guilty of a crime should be punished, or who makes decisions on legal matters',
          synonyms: ['justice', 'magistrate', 'try'],
          example: 'I just need to see a court order signed by a judge.',
        },
        {
          id: uuid(),
          en: 'knowledge',
          ua: 'знання',
          transcription: '[ˈnɒlɪdʒ]',
          definition:
            'facts, information, and skills acquired through experience or education; the theoretical or practical understanding of a subject',
          synonyms: ['education', 'information', 'command'],
          example: 'Knowledge is so cool he bought me a skateboard for my birthday!',
        },
        {
          id: uuid(),
          en: 'negotiate',
          ua: 'вести переговори',
          transcription: '[nəˈgəʊʃieɪt]',
          definition:
            'to have formal discussions with someone in order to reach an agreement with them',
          synonyms: ['deal', 'bargain', 'agree'],
          example: 'They have refused to negotiate on this issue.',
        },
      ],
      practice: [
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `My husband is the main accountant in this firm. He $$ you with your bank account.`,
          en: `My husband is the main accountant in this firm. He can help you with your bank account.`,
          ua: `Мій чоловік головний бухгалтер в цій фірмі. Він може допомогти з вашим банківським рахунком.`,
          variants: ['help can', 'can helping', 'can help'],
          placeholder: 'possibility',
          multiselect: [],
          correctVariant: 'can help',
          hint: 'can help',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `The chairman $$ with this company right now.`,
          en: `The chairman can negotiate with this company right now.`,
          ua: `Голова може вести переговори з цією компанією прямо зараз`,
          variants: ['can negotiate', 'can to negotiate', 'can negotiates'],
          multiselect: [],
          correctVariant: 'can negotiate',
          hint: 'can negotiate',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `She $$ this incompetent lad last week, why didn't she do that?`,
          en: `She could fire this incompetent lad last week, why didn't she do that?`,
          ua: `Вона могла звільнити цього некомпетентного хлопця минулого тижня, чому вона цього не зробила?`,
          placeholder: 'fire (possibility)',
          multiselect: [],
          variants: ['could fire', 'can fire', 'might fire'],
          correctVariant: 'could fire',
          hint: 'could fire',
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `Holly can try to change the judge's mind.`,
          ua: `Холлі може спробувати змінити думку судді.`,
          variants: [],
          multiselect: [
            {
              variants: [`Holly couldn't try`, `Holly could try`, `Holly can try`],
              correctVariant: 'Holly can try',
            },
            {
              variants: [`to change the`, `changed the`, `change the`],
              correctVariant: 'to change the',
            },
            {
              variants: [`judges' mind.`, `judge's mind.`, `judges mind.`],
              correctVariant: `judge's mind.`,
            },
          ],
          correctVariant: '',
          hint: `Holly can try to change the judge's mind.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `Peter can to work as an insurance agent and have flexible hours.`,
          en: `Peter can work as an insurance agent and have flexible hours.`,
          ua: `Пітер може працювати страховим агентом і мати гнучкий графік.`,
          variants: [],
          multiselect: [],
          correctVariant: 'Peter can work as an insurance agent and have flexible hours.',
          hint: 'Peter can work as an insurance agent and have flexible hours.',
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `We $$ have a break right now, we have too much stuff to do.`,
          en: `We can't have a break right now, we have too much stuff to do.`,
          ua: `Зараз ми не можемо відпочити, у нас надто багато справ.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you complete this task as quickly as possible?`,
          en: `Could you complete this task as quickly as possible?`,
          ua: `Чи могли б ви виконати це завдання якомога швидше?`,
          variants: [],
          multiselect: [],
          correctVariant: 'could',
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `They $$ you about your ambitions during your job interview.`,
          en: `They can ask you about your ambitions during your job interview.`,
          ua: `Розкажуть вам про ваші цілі під час співбесіди.`,
          variants: ['can ask', 'can to ask', 'could asked'],
          multiselect: [],
          correctVariant: 'can ask',
          hint: 'can ask',
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `This famous judge cans deal with the most difficult tasks.`,
          en: `This famous judge can deal with the most difficult tasks.`,
          ua: `Цей знаменитий суддя може впоратися з найскладнішими завданнями.`,
          variants: [],
          multiselect: [],
          hint: `This famous judge can deal with the most difficult tasks.`,
          correctVariant: `This famous judge can deal with the most difficult tasks.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ share my sacred knowledge with you, you’re too young for that.`,
          en: `I can't share my sacred knowledge with you, you’re too young for that.`,
          ua: `Я не можу поділитися з тобою своїми священними знаннями, ти ще занадто молодий для цього.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you help me to apply for this job?`,
          en: `Could you help me to apply for this job?`,
          ua: `Чи можете ви допомогти мені подати заявку на цю роботу?`,
          placeholder: 'possibility',
          variants: ['You can help', 'You could help', 'Could you help'],
          multiselect: [],
          correctVariant: `could`,
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `I can't be an accountant, it's too boring.`,
          ua: `Я не можу бути бухгалтером, це занадто нудно.`,
          variants: [],
          multiselect: [
            {
              variants: [`I don't can be`, `I can't be`, `I not can be`],
              correctVariant: `I can't be`,
            },
            {
              variants: [`a accountant`, `accountant`, `an accountant`],
              correctVariant: 'an accountant',
            },
            {
              variants: [`he's too`, `it's too`, `she's too`],
              correctVariant: `it's too`,
            },
            {
              variants: [`boring.`, `a boring.`, `the boring.`],
              correctVariant: `boring.`,
            },
          ],
          correctVariant: '',
          hint: `I can't be an accountant, it's too boring.`,
        },
        {
          id: uuid(),
          en: `I could deal with more problems when I was younger.`,
          ua: `Я міг впоратися з більшими проблемами, коли був молодше.`,
          type: PracticeTypes.CONSTRUCT,
          variants: [],
          multiselect: [
            {
              variants: [`I can dealt`, `I can deal`, `I could deal`],
              correctVariant: `I could deal`,
            },
            {
              variants: [`on more`, `from more`, `with more`],
              correctVariant: 'with more',
            },
            {
              variants: [`problem when`, `problem's when`, `problems when`],
              correctVariant: `problems when`,
            },
            {
              variants: [`I did younger.`, `I was younger.`, `I could younger.`],
              correctVariant: `I was younger.`,
            },
          ],
          correctVariant: '',
          hint: `I could deal with more problems when I was younger.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ apply for this job now. I have a kid waiting for me at home and no time at all.`,
          en: `I can't apply for this job now. I have a kid waiting for me at home and no time at all.`,
          ua: `Зараз я не можу претендувати на цю роботу. Мене вдома чекає дитина, а часу немає.`,
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not`,
          placeholder: 'possibility',
          hint: `can't`,
        },
      ],
    },
    status: LESSON_STATUS.NOT_STARTED,
    imageName: 'job',
  },
  {
    id: uuid(),
    number: 2,
    slug: 'Working',
    topic: 'Working',
    lessonContent: {
      vocabulary: [
        {
          id: uuid(),
          en: 'accomplish',
          ua: 'виконувати',
          transcription: '[əˈkʌmplɪʃ]',
          definition: 'achieve or complete successfully',
          synonyms: ['make', 'commit', 'carry out'],
          example: 'Think of what you could accomplish with a real budget.',
        },
        {
          id: uuid(),
          en: 'accountant',
          ua: 'бухгалтер',
          transcription: '[əˈkaʊntənt]',
          definition: 'a person whose job is to keep or inspect financial accounts',
          synonyms: ['auditor', 'comptroller', 'controller'],
          example: `Hi, my name is Jae Park. I used to be a Computer Science major but now I'm an accountant.`,
        },
        {
          id: uuid(),
          en: 'ambition',
          ua: 'ціль',
          transcription: '[æmˈbɪʃən]',
          definition: 'a strong desire to do or achieve something',
          synonyms: ['goal', 'dream', 'vision'],
          example:
            'He lost his ambition and forgot everything but his love for this unworthy woman.',
        },
        {
          id: uuid(),
          en: 'apply for',
          ua: 'подавати заявку',
          transcription: '[əˈplaɪ fɔːr]',
          definition: 'to make a formal application or request',
          synonyms: ['ask', 'demand'],
          example: 'Any student could apply for a scholarship.',
        },
        {
          id: uuid(),
          en: 'break',
          ua: 'перерва',
          transcription: '[breɪk]',
          definition:
            'to interrupt or to stop something for a short period: a period of time when you stop working in order to rest, eat etc',
          synonyms: ['intermission', 'recess', 'part'],
          example:
            'She was taking back a library book when she tripped and fell to the ground breaking both her shoulder and part of her upper left arm .',
        },
        {
          id: uuid(),
          en: 'chairman',
          ua: 'голова',
          transcription: '[ˈtʃeəmən]',
          definition: 'a person chosen to preside over a meeting',
          synonyms: ['speaker', 'chairperson', 'chair'],
          example: 'Archibald is the chairman , president and chief executive of the company.',
        },
        {
          id: uuid(),
          en: 'deal with',
          ua: `впоратись з`,
          transcription: '[diːl wɪð]',
          definition:
            'if you deal with an unpleasant emotion or an emotionally difficult situation, you recognize it, and remain calm and in control of yourself in spite of it',
          synonyms: ['manage', 'handle', 'take on'],
          example: `He's a hard man to deal with.`,
        },
        {
          id: uuid(),
          en: 'fashion designer',
          ua: 'модельєр',
          transcription: '[ˈfæʃən dɪˈzaɪnər]',
          definition: 'a person who designs high-fashion clothing',
          synonyms: ['designer', 'Couturier'],
          example:
            'Like other artists, fashion designers are somewhat sensitive and can be competitive.',
        },
        {
          id: uuid(),
          en: 'fire',
          ua: 'звільняти',
          transcription: '[faɪər]',
          definition:
            'the state of burning that produces flames that send out heat and light, and might produce smoke; to remove someone from their job',
          synonyms: ['terminate', 'dismiss', 'can'],
          example: `You can't fire somebody because he follows his heart.`,
        },
        {
          id: uuid(),
          en: 'flexible hours',
          ua: 'гнучкий графік',
          transcription: '[ˈfleksɪbl̩ aʊərz]',
          definition: 'flexible hours allow workers to alter workday start and finish times',
          synonyms: ['Flextime'],
          example: 'Flexible hours benefit everyone.',
        },
        {
          id: uuid(),
          en: 'insurance agent',
          ua: 'страховий агент',
          transcription: '[ɪnˈʃɔːrənts ˈeɪdʒənt]',
          definition: 'a person employed to sell insurance policies',
          synonyms: ['underwriter'],
          example:
            'A well-designed succession plan will likely involve other professionals such as an attorney, appraiser and insurance agent .',
        },
        {
          id: uuid(),
          en: 'job interview',
          ua: 'співбесіда',
          transcription: '[dʒɒb ˈɪntəvjuː]',
          definition:
            'a formal meeting in which an applicant is asked questions to determine their suitability for a particular job',
          synonyms: ['job hunting'],
          example: `She talked constantly, wouldn't accept authority and had such a short span of attention that she'd probably wander off to make herself a coffee during the initial job interview`,
        },
        {
          id: uuid(),
          en: 'judge',
          ua: 'суддя',
          transcription: '[dʒʌdʒ]',
          definition:
            'a person who is in charge of a trial in a court and decides how a person who is guilty of a crime should be punished, or who makes decisions on legal matters',
          synonyms: ['justice', 'magistrate', 'try'],
          example: 'I just need to see a court order signed by a judge.',
        },
        {
          id: uuid(),
          en: 'knowledge',
          ua: 'знання',
          transcription: '[ˈnɒlɪdʒ]',
          definition:
            'facts, information, and skills acquired through experience or education; the theoretical or practical understanding of a subject',
          synonyms: ['education', 'information', 'command'],
          example: 'Knowledge is so cool he bought me a skateboard for my birthday!',
        },
        {
          id: uuid(),
          en: 'negotiate',
          ua: 'вести переговори',
          transcription: '[nəˈgəʊʃieɪt]',
          definition:
            'to have formal discussions with someone in order to reach an agreement with them',
          synonyms: ['deal', 'bargain', 'agree'],
          example: 'They have refused to negotiate on this issue.',
        },
      ],
      practice: [
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `My husband is the main accountant in this firm. He $$ you with your bank account.`,
          en: `My husband is the main accountant in this firm. He can help you with your bank account.`,
          ua: `Мій чоловік головний бухгалтер в цій фірмі. Він може допомогти з вашим банківським рахунком.`,
          variants: ['help can', 'can helping', 'can help'],
          placeholder: 'possibility',
          multiselect: [],
          correctVariant: 'can help',
          hint: 'can help',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `The chairman $$ with this company right now.`,
          en: `The chairman can negotiate with this company right now.`,
          ua: `Голова може вести переговори з цією компанією прямо зараз`,
          variants: ['can negotiate', 'can to negotiate', 'can negotiates'],
          multiselect: [],
          correctVariant: 'can negotiate',
          hint: 'can negotiate',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `She $$ this incompetent lad last week, why didn't she do that?`,
          en: `She could fire this incompetent lad last week, why didn't she do that?`,
          ua: `Вона могла звільнити цього некомпетентного хлопця минулого тижня, чому вона цього не зробила?`,
          placeholder: 'fire (possibility)',
          multiselect: [],
          variants: ['could fire', 'can fire', 'might fire'],
          correctVariant: 'could fire',
          hint: 'could fire',
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `Holly can try to change the judge's mind.`,
          ua: `Холлі може спробувати змінити думку судді.`,
          variants: [],
          multiselect: [
            {
              variants: [`Holly couldn't try`, `Holly could try`, `Holly can try`],
              correctVariant: 'Holly can try',
            },
            {
              variants: [`to change the`, `changed the`, `change the`],
              correctVariant: 'to change the',
            },
            {
              variants: [`judges' mind.`, `judge's mind.`, `judges mind.`],
              correctVariant: `judge's mind.`,
            },
          ],
          correctVariant: '',
          hint: `Holly can try to change the judge's mind.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `Peter can to work as an insurance agent and have flexible hours.`,
          en: `Peter can work as an insurance agent and have flexible hours.`,
          ua: `Пітер може працювати страховим агентом і мати гнучкий графік.`,
          variants: [],
          multiselect: [],
          correctVariant: 'Peter can work as an insurance agent and have flexible hours.',
          hint: 'Peter can work as an insurance agent and have flexible hours.',
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `We $$ have a break right now, we have too much stuff to do.`,
          en: `We can't have a break right now, we have too much stuff to do.`,
          ua: `Зараз ми не можемо відпочити, у нас надто багато справ.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you complete this task as quickly as possible?`,
          en: `Could you complete this task as quickly as possible?`,
          ua: `Чи могли б ви виконати це завдання якомога швидше?`,
          variants: [],
          multiselect: [],
          correctVariant: 'could',
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `They $$ you about your ambitions during your job interview.`,
          en: `They can ask you about your ambitions during your job interview.`,
          ua: `Розкажуть вам про ваші цілі під час співбесіди.`,
          variants: ['can ask', 'can to ask', 'could asked'],
          multiselect: [],
          correctVariant: 'can ask',
          hint: 'can ask',
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `This famous judge cans deal with the most difficult tasks.`,
          en: `This famous judge can deal with the most difficult tasks.`,
          ua: `Цей знаменитий суддя може впоратися з найскладнішими завданнями.`,
          variants: [],
          multiselect: [],
          hint: `This famous judge can deal with the most difficult tasks.`,
          correctVariant: `This famous judge can deal with the most difficult tasks.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ share my sacred knowledge with you, you’re too young for that.`,
          en: `I can't share my sacred knowledge with you, you’re too young for that.`,
          ua: `Я не можу поділитися з тобою своїми священними знаннями, ти ще занадто молодий для цього.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you help me to apply for this job?`,
          en: `Could you help me to apply for this job?`,
          ua: `Чи можете ви допомогти мені подати заявку на цю роботу?`,
          placeholder: 'possibility',
          variants: ['You can help', 'You could help', 'Could you help'],
          multiselect: [],
          correctVariant: `could`,
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `I can't be an accountant, it's too boring.`,
          ua: `Я не можу бути бухгалтером, це занадто нудно.`,
          variants: [],
          multiselect: [
            {
              variants: [`I don't can be`, `I can't be`, `I not can be`],
              correctVariant: `I can't be`,
            },
            {
              variants: [`a accountant`, `accountant`, `an accountant`],
              correctVariant: 'an accountant',
            },
            {
              variants: [`he's too`, `it's too`, `she's too`],
              correctVariant: `it's too`,
            },
            {
              variants: [`boring.`, `a boring.`, `the boring.`],
              correctVariant: `boring.`,
            },
          ],
          correctVariant: '',
          hint: `I can't be an accountant, it's too boring.`,
        },
        {
          id: uuid(),
          en: `I could deal with more problems when I was younger.`,
          ua: `Я міг впоратися з більшими проблемами, коли був молодше.`,
          type: PracticeTypes.CONSTRUCT,
          variants: [],
          multiselect: [
            {
              variants: [`I can dealt`, `I can deal`, `I could deal`],
              correctVariant: `I could deal`,
            },
            {
              variants: [`on more`, `from more`, `with more`],
              correctVariant: 'with more',
            },
            {
              variants: [`problem when`, `problem's when`, `problems when`],
              correctVariant: `problems when`,
            },
            {
              variants: [`I did younger.`, `I was younger.`, `I could younger.`],
              correctVariant: `I was younger.`,
            },
          ],
          correctVariant: '',
          hint: `I could deal with more problems when I was younger.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ apply for this job now. I have a kid waiting for me at home and no time at all.`,
          en: `I can't apply for this job now. I have a kid waiting for me at home and no time at all.`,
          ua: `Зараз я не можу претендувати на цю роботу. Мене вдома чекає дитина, а часу немає.`,
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not`,
          placeholder: 'possibility',
          hint: `can't`,
        },
      ],
    },
    status: LESSON_STATUS.IN_PROGRESS,
    imageName: 'Working',
  },
  {
    id: uuid(),
    number: 3,
    slug: 'Work',
    topic: 'Work',
    status: LESSON_STATUS.DONE,
    imageName: 'Working',
    lessonContent: {
      vocabulary: [
        {
          id: uuid(),
          en: 'accomplish',
          ua: 'виконувати',
          transcription: '[əˈkʌmplɪʃ]',
          definition: 'achieve or complete successfully',
          synonyms: ['make', 'commit', 'carry out'],
          example: 'Think of what you could accomplish with a real budget.',
        },
        {
          id: uuid(),
          en: 'accountant',
          ua: 'бухгалтер',
          transcription: '[əˈkaʊntənt]',
          definition: 'a person whose job is to keep or inspect financial accounts',
          synonyms: ['auditor', 'comptroller', 'controller'],
          example: `Hi, my name is Jae Park. I used to be a Computer Science major but now I'm an accountant.`,
        },
        {
          id: uuid(),
          en: 'ambition',
          ua: 'ціль',
          transcription: '[æmˈbɪʃən]',
          definition: 'a strong desire to do or achieve something',
          synonyms: ['goal', 'dream', 'vision'],
          example:
            'He lost his ambition and forgot everything but his love for this unworthy woman.',
        },
        {
          id: uuid(),
          en: 'apply for',
          ua: 'подавати заявку',
          transcription: '[əˈplaɪ fɔːr]',
          definition: 'to make a formal application or request',
          synonyms: ['ask', 'demand'],
          example: 'Any student could apply for a scholarship.',
        },
        {
          id: uuid(),
          en: 'break',
          ua: 'перерва',
          transcription: '[breɪk]',
          definition:
            'to interrupt or to stop something for a short period: a period of time when you stop working in order to rest, eat etc',
          synonyms: ['intermission', 'recess', 'part'],
          example:
            'She was taking back a library book when she tripped and fell to the ground breaking both her shoulder and part of her upper left arm .',
        },
        {
          id: uuid(),
          en: 'chairman',
          ua: 'голова',
          transcription: '[ˈtʃeəmən]',
          definition: 'a person chosen to preside over a meeting',
          synonyms: ['speaker', 'chairperson', 'chair'],
          example: 'Archibald is the chairman , president and chief executive of the company.',
        },
        {
          id: uuid(),
          en: 'deal with',
          ua: `впоратись з`,
          transcription: '[diːl wɪð]',
          definition:
            'if you deal with an unpleasant emotion or an emotionally difficult situation, you recognize it, and remain calm and in control of yourself in spite of it',
          synonyms: ['manage', 'handle', 'take on'],
          example: `He's a hard man to deal with.`,
        },
        {
          id: uuid(),
          en: 'fashion designer',
          ua: 'модельєр',
          transcription: '[ˈfæʃən dɪˈzaɪnər]',
          definition: 'a person who designs high-fashion clothing',
          synonyms: ['designer', 'Couturier'],
          example:
            'Like other artists, fashion designers are somewhat sensitive and can be competitive.',
        },
        {
          id: uuid(),
          en: 'fire',
          ua: 'звільняти',
          transcription: '[faɪər]',
          definition:
            'the state of burning that produces flames that send out heat and light, and might produce smoke; to remove someone from their job',
          synonyms: ['terminate', 'dismiss', 'can'],
          example: `You can't fire somebody because he follows his heart.`,
        },
        {
          id: uuid(),
          en: 'flexible hours',
          ua: 'гнучкий графік',
          transcription: '[ˈfleksɪbl̩ aʊərz]',
          definition: 'flexible hours allow workers to alter workday start and finish times',
          synonyms: ['Flextime'],
          example: 'Flexible hours benefit everyone.',
        },
        {
          id: uuid(),
          en: 'insurance agent',
          ua: 'страховий агент',
          transcription: '[ɪnˈʃɔːrənts ˈeɪdʒənt]',
          definition: 'a person employed to sell insurance policies',
          synonyms: ['underwriter'],
          example:
            'A well-designed succession plan will likely involve other professionals such as an attorney, appraiser and insurance agent .',
        },
        {
          id: uuid(),
          en: 'job interview',
          ua: 'співбесіда',
          transcription: '[dʒɒb ˈɪntəvjuː]',
          definition:
            'a formal meeting in which an applicant is asked questions to determine their suitability for a particular job',
          synonyms: ['job hunting'],
          example: `She talked constantly, wouldn't accept authority and had such a short span of attention that she'd probably wander off to make herself a coffee during the initial job interview`,
        },
        {
          id: uuid(),
          en: 'judge',
          ua: 'суддя',
          transcription: '[dʒʌdʒ]',
          definition:
            'a person who is in charge of a trial in a court and decides how a person who is guilty of a crime should be punished, or who makes decisions on legal matters',
          synonyms: ['justice', 'magistrate', 'try'],
          example: 'I just need to see a court order signed by a judge.',
        },
        {
          id: uuid(),
          en: 'knowledge',
          ua: 'знання',
          transcription: '[ˈnɒlɪdʒ]',
          definition:
            'facts, information, and skills acquired through experience or education; the theoretical or practical understanding of a subject',
          synonyms: ['education', 'information', 'command'],
          example: 'Knowledge is so cool he bought me a skateboard for my birthday!',
        },
        {
          id: uuid(),
          en: 'negotiate',
          ua: 'вести переговори',
          transcription: '[nəˈgəʊʃieɪt]',
          definition:
            'to have formal discussions with someone in order to reach an agreement with them',
          synonyms: ['deal', 'bargain', 'agree'],
          example: 'They have refused to negotiate on this issue.',
        },
      ],
      practice: [
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `My husband is the main accountant in this firm. He $$ you with your bank account.`,
          en: `My husband is the main accountant in this firm. He can help you with your bank account.`,
          ua: `Мій чоловік головний бухгалтер в цій фірмі. Він може допомогти з вашим банківським рахунком.`,
          variants: ['help can', 'can helping', 'can help'],
          placeholder: 'possibility',
          multiselect: [],
          correctVariant: 'can help',
          hint: 'can help',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `The chairman $$ with this company right now.`,
          en: `The chairman can negotiate with this company right now.`,
          ua: `Голова може вести переговори з цією компанією прямо зараз`,
          variants: ['can negotiate', 'can to negotiate', 'can negotiates'],
          multiselect: [],
          correctVariant: 'can negotiate',
          hint: 'can negotiate',
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `She $$ this incompetent lad last week, why didn't she do that?`,
          en: `She could fire this incompetent lad last week, why didn't she do that?`,
          ua: `Вона могла звільнити цього некомпетентного хлопця минулого тижня, чому вона цього не зробила?`,
          placeholder: 'fire (possibility)',
          multiselect: [],
          variants: ['could fire', 'can fire', 'might fire'],
          correctVariant: 'could fire',
          hint: 'could fire',
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `Holly can try to change the judge's mind.`,
          ua: `Холлі може спробувати змінити думку судді.`,
          variants: [],
          multiselect: [
            {
              variants: [`Holly couldn't try`, `Holly could try`, `Holly can try`],
              correctVariant: 'Holly can try',
            },
            {
              variants: [`to change the`, `changed the`, `change the`],
              correctVariant: 'to change the',
            },
            {
              variants: [`judges' mind.`, `judge's mind.`, `judges mind.`],
              correctVariant: `judge's mind.`,
            },
          ],
          correctVariant: '',
          hint: `Holly can try to change the judge's mind.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `Peter can to work as an insurance agent and have flexible hours.`,
          en: `Peter can work as an insurance agent and have flexible hours.`,
          ua: `Пітер може працювати страховим агентом і мати гнучкий графік.`,
          variants: [],
          multiselect: [],
          correctVariant: 'Peter can work as an insurance agent and have flexible hours.',
          hint: 'Peter can work as an insurance agent and have flexible hours.',
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `We $$ have a break right now, we have too much stuff to do.`,
          en: `We can't have a break right now, we have too much stuff to do.`,
          ua: `Зараз ми не можемо відпочити, у нас надто багато справ.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you complete this task as quickly as possible?`,
          en: `Could you complete this task as quickly as possible?`,
          ua: `Чи могли б ви виконати це завдання якомога швидше?`,
          variants: [],
          multiselect: [],
          correctVariant: 'could',
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.SELECT_ONE,
          missed: `They $$ you about your ambitions during your job interview.`,
          en: `They can ask you about your ambitions during your job interview.`,
          ua: `Розкажуть вам про ваші цілі під час співбесіди.`,
          variants: ['can ask', 'can to ask', 'could asked'],
          multiselect: [],
          correctVariant: 'can ask',
          hint: 'can ask',
        },
        {
          id: uuid(),
          type: PracticeTypes.CORRECT,
          missed: `This famous judge cans deal with the most difficult tasks.`,
          en: `This famous judge can deal with the most difficult tasks.`,
          ua: `Цей знаменитий суддя може впоратися з найскладнішими завданнями.`,
          variants: [],
          multiselect: [],
          hint: `This famous judge can deal with the most difficult tasks.`,
          correctVariant: `This famous judge can deal with the most difficult tasks.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ share my sacred knowledge with you, you’re too young for that.`,
          en: `I can't share my sacred knowledge with you, you’re too young for that.`,
          ua: `Я не можу поділитися з тобою своїми священними знаннями, ти ще занадто молодий для цього.`,
          placeholder: 'possibility',
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not/cannot`,
          hint: `can't`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `$$ you help me to apply for this job?`,
          en: `Could you help me to apply for this job?`,
          ua: `Чи можете ви допомогти мені подати заявку на цю роботу?`,
          placeholder: 'possibility',
          variants: ['You can help', 'You could help', 'Could you help'],
          multiselect: [],
          correctVariant: `could`,
          hint: `could`,
        },
        {
          id: uuid(),
          type: PracticeTypes.CONSTRUCT,
          en: `I can't be an accountant, it's too boring.`,
          ua: `Я не можу бути бухгалтером, це занадто нудно.`,
          variants: [],
          multiselect: [
            {
              variants: [`I don't can be`, `I can't be`, `I not can be`],
              correctVariant: `I can't be`,
            },
            {
              variants: [`a accountant`, `accountant`, `an accountant`],
              correctVariant: 'an accountant',
            },
            {
              variants: [`he's too`, `it's too`, `she's too`],
              correctVariant: `it's too`,
            },
            {
              variants: [`boring.`, `a boring.`, `the boring.`],
              correctVariant: `boring.`,
            },
          ],
          correctVariant: '',
          hint: `I can't be an accountant, it's too boring.`,
        },
        {
          id: uuid(),
          en: `I could deal with more problems when I was younger.`,
          ua: `Я міг впоратися з більшими проблемами, коли був молодше.`,
          type: PracticeTypes.CONSTRUCT,
          variants: [],
          multiselect: [
            {
              variants: [`I can dealt`, `I can deal`, `I could deal`],
              correctVariant: `I could deal`,
            },
            {
              variants: [`on more`, `from more`, `with more`],
              correctVariant: 'with more',
            },
            {
              variants: [`problem when`, `problem's when`, `problems when`],
              correctVariant: `problems when`,
            },
            {
              variants: [`I did younger.`, `I was younger.`, `I could younger.`],
              correctVariant: `I was younger.`,
            },
          ],
          correctVariant: '',
          hint: `I could deal with more problems when I was younger.`,
        },
        {
          id: uuid(),
          type: PracticeTypes.INPUT,
          missed: `I $$ apply for this job now. I have a kid waiting for me at home and no time at all.`,
          en: `I can't apply for this job now. I have a kid waiting for me at home and no time at all.`,
          ua: `Зараз я не можу претендувати на цю роботу. Мене вдома чекає дитина, а часу немає.`,
          variants: [],
          multiselect: [],
          correctVariant: `can't/can not`,
          placeholder: 'possibility',
          hint: `can't`,
        },
      ],
    },
  },
]

export const WelcomePagePreferences = [
  {
    id: '1',
    title: 'Тисячі слів',
    subtitle: 'Саме ті слова, що знадобляться у повсякденному спілкуванні.',
    imageName: 'words',
  },
  {
    id: '2',
    title: 'Безліч актуальних тем',
    subtitle: 'Ми підібрали саме ті теми які знадобляться як повсякденні так і на роботі.',
    imageName: 'topic',
  },
  {
    id: '3',
    title: 'Лише 15 хвилин щодня',
    subtitle: 'Щоденні заняття допоможуть вам швидше поповнити свій словниковий запас.',
    imageName: 'fifteen-minutes',
  },
  {
    id: '4',
    title: 'Різноманітні тренування',
    subtitle: 'Ми підготували цікаві і дієві тренування.',
    imageName: 'training',
  },
]

export const DashboardItems = [
  {
    id: '1',
    title: 'Уроки',
    subtitle: 'Тематичні уроки',
    imageName: 'lessons',
    path: ROUTES.LESSONS,
  },
  {
    id: '2',
    title: 'Нові слова',
    subtitle: 'Вивчити нові слова',
    imageName: 'vocabulary',
    path: ROUTES.VOCABULARY,
  },
  {
    id: '3',
    title: 'Граматика',
    subtitle: 'Без знань граматики нікуди',
    imageName: 'grammar',
    path: ROUTES.GRAMMAR,
  },
  {
    id: '4',
    title: 'Словник',
    subtitle: 'Список вивчених слів',
    imageName: 'dictionary',
    path: ROUTES.DICTIONARY,
  },
]

export const lessonsSubtitles = {
  0: `Для початку вивчимо кілька нових слів`,
  1: `А зараз перевіримо знання нових слів`,
  2: 'І на останок попрактикуймося',
}

export const PracticeTasks = {
  input: 'Write the correct form',
  select_one: 'Choose the correct alternative',
  correct: 'Correct the mistake',
  construct: 'Put together',
  translate: 'Translate the phrase',
}

// Forest data
