'use client'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import GlobalStyles from '@/styles/GlobalStyles'
import TopNavbar from '@/components/__features__/TopNavbar'

const roboto = Roboto({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700'],
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className} suppressHydrationWarning>
        <Providers>
          <GlobalStyles />
          <TopNavbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
